### PR TITLE
fix travis test

### PR DESCRIPTION
**Pull request by jnozsc**
- [x] make the CI works again
- [x] drop python 2.6 and python 3.3, 3.4 due to EOL 
- [x] fix `werkzeug` 1.0 compatible  issue 
- [x] pin some `werkzeug` version, since old version `flask` has compatible  issue with `werkzeug` 1.0
- [x] pin some `flask` version, since old version `flask` does not fully support python 3.7+

### CODE REVIEW

**Comment by zhanwenchen** [comment]
@jarus @jcomo is this project still maintained?

**Comment by jcomo** [comment]
@zhanwenchen I don't have the bandwidth to actively maintain this project. It hasn't seen much activity recently

**Comment by Sispheor** [comment]
Could you create a new release that include this fix and push to pypi?
Thanks a lot !

**Comment by filipallberg** [comment]
> 
> 
> @zhanwenchen I don't have the bandwidth to actively maintain this project. It hasn't seen much activity recently

Super happy this got merged, but it'd be lovely to see it pushed to pypi as well!

**Comment by jcomo** [comment]
Done. 0.8.0 is available in pypi now

**Pull request merged**
