### PR TITLE
Use a more descriptive error when signals is not supported

### PR DESCRIPTION
**Pull request by jcomo**
Addresses #99.

@maxtortime does this seem better to you?

### CODE REVIEW

**Comment by maxtortime** [comment]
I think it is good instructions because user can know next jobs for resolving their exceptions.

**Comment by jcomo** [comment]
👍 thanks for the feedback!

**Comment by maxtortime** [comment]
I found about requirements(installing `blinker`) for using `assert_template_used ` bottom of https://pythonhosted.org/Flask-Testing/ . I think it is better for user that link method words to API explanation. May I create pull request for document?

**Comment by jcomo** [comment]
In this case the error message and the docs are saying the same thing. I feel that linking to that page would be redundant

**Pull request merged**
